server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

#server.port=8761
#
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#
#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF