server:
    port: 8081
#spring:jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_fornecedor
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driver-class-name
#spring.jpa.show-sql: true

spring:
    application:
        name: 'fornecedor'
    datasource:
        password: password
        username: root
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_fornecedor
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka