spring:
  application:
      name: 'loja'

eureka:
  client:
    preferIpAddress: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka